#!/bin/bash

NAME=${PWD##*docker-}
IMAGE_NAME=yokogawa/${NAME}
docker rm ${NAME}

set -x
if [ "${1}" = "bash" ]; then
    docker run -v ${PWD}:/work -i -t --entry-point="/bin/bash" --name=${NAME} ${IMAGE_NAME}
else
    docker run -d -v ${PWD}:/work -p 8080:8080 --name=${NAME} ${IMAGE_NAME} $@
fi
